spring:
  config:
    activate:
      on-profile: prod

  #임시적으로 h2 사용
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT:3306}/${RDS_DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        jdbc:
          time_zone: Asia/Seoul

oauth:
  kakao:
    frontend-redirect-uri: ${KAKAO_FRONTEND_REDIRECT_URI}